### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by nvreynolds** [avantcredit/avantcredit.github.io#1]
@robertzk what do you want to live here?

General repo wiki?
specific repo wikis?
dev team breakdown?
dev practices?
new hire resources?

**Comment by robertzk** [comment]
Check your private email

On Tue, Nov 10, 2015 at 10:17 AM, Nate R <notifications@github.com> wrote:

> @robertzk <https://github.com/robertzk> what do you want to live here?
>
> General repo wiki?
> specific repo wikis?
> dev team breakdown?
> dev practices?
> new hire resources?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avantcredit/avantcredit.github.io/issues/1>.
>



-- 
-Robert Krzyzanowski

**Comment by nvreynolds** [comment]
ahh didnt realize this was public.. makes sense thanks!
